### ISSUE TITLE
Main(NOTWORKING)

### ISSUE THREAD

**Issue by deinchapman** [deinchapman/textnovel-lonelystar#1]
The reason I uploaded this file it's because i tried making a textual novel using functions, but they didn't work they way i wanted them to be. If you could explain me why, i would appreciate that like you can't imagine.

**Comment by clovis1122** [comment]
@deinchapman I'll look into it but the usual workflow is that you'd open a pull request on GitHub and add me as a reviewer so I can look at the code and leave comments. This would all happen on a new branch outside of the `main` branch.

Here's a nice git tutorial (there're many out there): https://learngitbranching.js.org/

**Comment by clovis1122** [comment]
Checking the code now... I believe you want to call/invoke the function. For that, just add the parenthesis. Here's an example:

```
def Text1v1():
    (print("Today you went out to look for the moon.\n You only wish to the least delight yourself with it's beauty,"))

## more code...

if answer == 1: 
    print(Text1v1) 
else:
    print(Text1v1)
```

There's a difference between `Text1v1` and `Text1v1()`. The first one is a reference, the second one is invoking the function and returning the result.

(I believe python v2 used to have implicit function invocation like other programming languages... but this was removed in v3, and all function calls must be explicit with parenthesis).

**Comment by deinchapman** [comment]
> @deinchapman I'll look into it but the usual workflow is that you'd open a pull request on GitHub and add me as a reviewer so I can look at the code and leave comments. This would all happen on a new branch outside of the `main` branch.
> 
> Here's a nice git tutorial (there're many out there): https://learngitbranching.js.org/

I see, so whenever i have an issue like this i should open a new branch aside from the principal, and then create a pull request

**Comment by deinchapman** [comment]
> Checking the code now... I believe you want to call/invoke the function. For that, just add the parenthesis. Here's an example:
> 
> ```
> def Text1v1():
>     (print("Today you went out to look for the moon.\n You only wish to the least delight yourself with it's beauty,"))
> 
> ## more code...
> 
> if answer == 1: 
>     print(Text1v1) 
> else:
>     print(Text1v1)
> ```
> 
> There's a difference between `Text1v1` and `Text1v1()`. The first one is a reference, the second one is invoking the function and returning the result.
> 
> (I believe python v2 used to have implicit function invocation like other programming languages... but this was removed in v3, and all function calls must be explicit with parenthesis).

Cool, i'll try that out and see how it works

**Comment by deinchapman** [comment]
> > Checking the code now... I believe you want to call/invoke the function. For that, just add the parenthesis. Here's an example:
> > ```
> > def Text1v1():
> >     (print("Today you went out to look for the moon.\n You only wish to the least delight yourself with it's beauty,"))
> > 
> > ## more code...
> > 
> > if answer == 1: 
> >     print(Text1v1) 
> > else:
> >     print(Text1v1)
> > ```
> > 
> > 
> > There's a difference between `Text1v1` and `Text1v1()`. The first one is a reference, the second one is invoking the function and returning the result.
> > (I believe python v2 used to have implicit function invocation like other programming languages... but this was removed in v3, and all function calls must be explicit with parenthesis).
> 
> Cool, i'll try that out and see how it works

Yep, it worked

**Comment by clovis1122** [comment]
> > @deinchapman I'll look into it but the usual workflow is that you'd open a pull request on GitHub and add me as a reviewer so I can look at the code and leave comments. This would all happen on a new branch outside of the `main` branch.
> > Here's a nice git tutorial (there're many out there): https://learngitbranching.js.org/
> 
> I see, so whenever i have an issue like this i should open a new branch aside from the principal, and then create a pull request

Yes!

**Comment by clovis1122** [comment]
This is fixed. Closing!
