### ISSUE TITLE
It allows me to continue even when I don't type anything

### ISSUE THREAD

**Issue by clovis1122** [deinchapman/textnovel-lonelystar#2]
![image](https://github.com/deinchapman/textnovel-lonelystar/assets/22270042/04412fd3-3cc3-4a40-8d14-aca806cd8fad)

**Comment by deinchapman** [comment]
yes, actually that's what's intended to. The only point in the game where you are suppose to input an actual answer is when the game asks you to input (yes/no).

But the fact that you don't need to input anything to continue is part of game design, like trying to imitate the gameplay of the visualnovels created through renpy or else

**Comment by clovis1122** [comment]
What do you think about `Press <enter> to continue`? I think it better reflects how the functionality works right now. The current "Input anything to continue" prompt isn't accurate because even if I just press enter (which is usually not counted as "input"), it will continue.

**Comment by deinchapman** [comment]
> What do you think about `Press <enter> to continue`? I think it better reflects how the functionality works right now. The current "Input anything to continue" prompt isn't accurate because even if I just press enter (which is usually not counted as "input"), it will continue.

You are... TOTALLY right about that

some overenginering here and there like always

**Comment by clovis1122** [comment]
Technically fixed but leaving open so we can use this issue as an example for proper code review workflow.
