### ISSUE TITLE
Unify the existing files into a single `main.py` file

### ISSUE THREAD

**Issue by clovis1122** [deinchapman/textnovel-lonelystar#6]
We should unify all the current files into a single one. From what I saw in the other files `Main2.py` seems to be the latest version. Perhaps we can rename it `main.py` (lowercase) and remove the other files.
 
The benefit of having a single entry point via the main.py file is that you will have a unified entry point for the application so that you can do `python main.py` and it just works.

**Comment by deinchapman** [comment]
noted
